name: zielone_japko
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  uuid: ^4.5.1
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  go_router: ^7.0.2
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.6.3
  custom_lint: ^0.7.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  flutter_native_splash: ^2.4.1
  hive_ce_generator: ^1.8.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/images/splash_tea.png
  color: "#F4F3DF"
  android_12:
    image: assets/images/splash_tea.png
    color: "#F4F3DF"

